### ISSUE TITLE
POST /documents Timing Out

### ISSUE THREAD

**Issue by kevr** [kevr/hastebin#2]
The hastebin script is (at the time of this writing) timing out on a POST request while attempting to upload a text document to https://hastebin.com/documents.

This is not a bug in the script itself, but a service issue: Attempting to browse and use https://hastebin.com results in the same issue when attempting to save a paste.

As far as this script's code goes; there's nothing to be updated (yet).

**Comment by kevr** [comment]
We cannot do anything about this from an HTTP client perspective.

**Comment by kode54** [comment]
Is this still an issue? The site seems to work here? (Note: the domain appears to be behind CloudFlare.)

Edit: Oh. I see. The static content appears to work, but the actual API appears to be dead. Guess this site stopped being useful.

**Comment by kevr** [comment]
Yep. :(. I have emailed the website contact email, hopefully we can revive it.

**Comment by kevr** [comment]
Looks like hastebin is live again. I've re-uploaded the AUR package.

All hail hastebin!
