### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by ITCMD** [kevr/hastebin#4]
the readme.md states how to use it but not how to install it. Releases page does not contain a .deb or .sh file to download.

**Comment by kevr** [comment]
This was a small pet project of mine and I wasn't thinking of anybody really using it -- I'll add some documentation on how to install this. If you find any issues or things you'd like changed, please do make an issue for it!

You use a debian-based distribution, you say?

- To workaround for now, what you can do is place the `hastebin` python file anywhere in your `$PATH` with executable permissions set. For example, `sudo install -m755 hastebin /usr/local/bin/hastebin` would copy the file to `/usr/local/bin/hastebin` and set `755` permissions on it, which includes the execute bit. You must have `python3` on your system.

**Comment by kevr** [comment]
I added these instructions in here to the README for both root and a normal user. I'll make an issue related to setting up an actual install script or packages for some distributions. Thanks for the interest, @ITCMD!

**Comment by ITCMD** [comment]
Thanks for the instructions @kevr!
